name: Nuxt.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Install npm dependencies
      run: |
        cd src
        npm install
    - name: Nuxt Linter
      run: |
        cd src
        npm run lintfix
        npm run lint
    - name: Build Nuxt application
      run: |
        cd src
        npm run build
